workflow statistics
k8-proxy/k8-glasswall-rebuild pull request #37
Opened 2020-10-08 11:51 UTC by azopat

2020-10-08 12:33 UTC, yardenshoham requested changes

2020-10-08 12:33 UTC, yardenshoham commented on argo/README.md
>  kubectl apply -n argo-events -f minio-eventsource.yml -f minio-event-sensor.yml
```suggestion
kubectl apply -f minio-eventsource.yml -f minio-event-sensor.yml
```
Please update the README commands to use the `argo` namespace.

2020-10-08 12:33 UTC, yardenshoham commented on argo/README.md
>  kubectl apply -n argo-events -f minio-eventsource.yml -f minio-event-sensor.yml
I'm referring to lines `47-48`.

2020-10-09 09:42 UTC, azopat commented
done

2020-10-09 13:15 UTC, yardenshoham commented
@azopat also lines `47-48`.

2020-10-13 17:26 UTC, yardenshoham approved these changes

2020-10-13 19:41 UTC, merged